---
kind: pipeline
type: docker
name: inspiringhopechurch

steps:
  - name: build development site
    image: mastrbennett/cypress-browsers:node18-chrome105-ff104
    environment:
      GHOST_API_URL:
        from_secret: ghost_api_url
      GHOST_CONTENT_API_KEY:
        from_secret: ghost_content_api_key
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
      NODE_ENV: "production"
    commands:
      - git config pull.rebase false
      - git pull origin ${DRONE_COMMIT_REF}
      - npm ci --legacy-peer-deps # install cypress npm package without installing the binary
      # Set GATSBY_CPU_COUNT to low number to combat OOM failures with gatsby v4 + drone VPS
      - GATSBY_CPU_COUNT=2 gatsby build
    when:
      ref:
        - refs/heads/develop
      event:
        - push
        - merge
        - custom

  - name: build production site
    image: mastrbennett/cypress-browsers:node18-chrome105-ff104
    environment:
      GHOST_API_URL:
        from_secret: ghost_api_url
      GHOST_CONTENT_API_KEY:
        from_secret: ghost_content_api_key
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
      NODE_ENV: "production"
    commands:
      - git config pull.rebase false
      - git pull origin ${DRONE_COMMIT_REF}
      - npm ci --legacy-peer-deps # install cypress npm package without installing the binary
      # Set GATSBY_CPU_COUNT to low number to combat OOM failures with gatsby v4 + drone VPS
      - GATSBY_CPU_COUNT=2 gatsby build
    when:
      ref:
        - refs/tags/v*
        - refs/heads/main
      event:
        - push
        - tag
        - custom

  - name: test site
    image: mastrbennett/cypress-browsers:node18-chrome105-ff104
    environment:
      GHOST_API_URL:
        from_secret: ghost_api_url
      GHOST_CONTENT_API_KEY:
        from_secret: ghost_content_api_key
      NPM_AUTH_TOKEN:
        from_secret: npm_auth_token
      CYPRESS_RECORD_KEY:
        from_secret: cypress_record_key
      CI: "true"
    commands:
      - npm i --legacy-peer-deps
      - gatsby serve --no-color &
      - $(npm bin)/cypress install
      - npm run integration -- --record
    when:
      event:
        exclude:
          - tag

  # Deploy develop branch to development folder - dev.inspiringhopechurch.com
  - name: deploy development
    image: appleboy/drone-scp
    settings:
      host: inspiringhopechurch.com
      username:
        from_secret: ssh_deploy_user
      key:
        from_secret: ssh_deploy_key
      port: 22
      target: /var/www/inspiringhope.gatsby/public
      rm: false
      source: public/*
      strip_components: 1
    when:
      branch:
        - develop
      status:
        - success
        - failure

  # Deploy master branch to production folder - inspiringhopechurch.com
  - name: deploy production
    image: appleboy/drone-scp
    settings:
      host: inspiringhopechurch.com
      username:
        from_secret: ssh_deploy_user
      key:
        from_secret: ssh_deploy_key
      port: 22
      target: /var/www/${DRONE_REPO_NAME}/public
      rm: false
      source: public/*
      strip_components: 1
    when:
      event:
        - tag
        - custom
      status:
        - success

  - name: notify
    image: drillster/drone-email
    environment:
      EMAIL_USERNAME:
        from_secret: email_username
      EMAIL_PASSWORD:
        from_secret: email_password
    settings:
      host: smtp.mailgun.org
      port: 465
      from: drone@inspiringhopechurch.com
      subject: >
        {{ repo.name }} website deployment is a {{ build.status }}
      recipients:
        - admin@inspiringhopechurch.com
        - ben@inspiringhopechurch.com
        - mdharri2@gmail.com
    when:
      status:
        - success
        - failure

node:
  cypress: parallel
