---
kind: pipeline
type: docker
name: inspiringhope

steps:
- name: build
  # image: cypress/browsers:node14.15.0-chrome86-ff82
  image: mastrbennett/node-gatsby
  environment:
    GHOST_API_URL:
      from_secret: ghost_api_url
    GHOST_CONTENT_API_KEY:
      from_secret: ghost_content_api_key
    NPM_AUTH_TOKEN:
      from_secret: npm_auth_token
    CYPRESS_RECORD_KEY:
      from_secret: cypress_record_key
    CI: true
  commands:
  # - apk add git autoconf automake pkgconfig libpng libjpeg libtool gcc g++ make file nasm
  # - npm i -g gatsby-cli
  - git pull origin master
  - npm i
  - gatsby build
  # - gatsby serve &
  # - npm run integration -- --parallel
  when:
    branch:
    - master
    event:
    - push
    - merge
    - custom

- name: deploy
  image: appleboy/drone-scp
  settings:
    host: inspiringhopechurch.com
    username:
      from_secret: ssh_deploy_user
    key:
      from_secret: ssh_deploy_key
    port: 22
    target: /var/www/${DRONE_REPO_NAME}/public
    rm: true
    source: public/*

# - name: notify
#     image: drillster/drone-email
#     host: mail.inspiringhopechurch.com
#     username: orville
#     password:
#       from_secret: mail_password
#     from: drone@inspiringhopechurch.com
#     recipients: [ admin@inspiringhopechurch.com  ]
#     when:
#       status: [ changed, failure ]
node:
  cypress: parallel
