import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faAngleDown,
  faAngleUp,
  faBadgePercent,
  faCommentAltLines,
  faEnvelope,
  faHeart,
  faMapMarkerAlt,
  faUser,
  faPaperPlane,
  faPhone,
} from "@fortawesome/pro-solid-svg-icons";
import {
  faFacebook,
  faFacebookF,
  faTwitter,
  faLinkedinIn,
  faReact,
  faNode,
  faLaravel,
  faDocker,
  faFreebsd,
  faFedora,
  faJenkins,
  faWindows,
  faUbuntu,
  faSass,
  faStripe,
  faBlackberry,
  faGit,
  faDigitalOcean,
  faLinode,
} from "@fortawesome/free-brands-svg-icons";

// Initialize icon library to use throughout our app
library.add(
  faAngleDown,
  faAngleUp,
  faBadgePercent,
  faCommentAltLines,
  faEnvelope,
  faHeart,
  faMapMarkerAlt,
  faUser,
  faPaperPlane,
  faPhone,
  faFacebook,
  faFacebookF,
  faTwitter,
  faLinkedinIn,
  faReact,
  faNode,
  faLaravel,
  faDocker,
  faFreebsd,
  faFedora,
  faJenkins,
  faWindows,
  faUbuntu,
  faSass,
  faStripe,
  faBlackberry,
  faGit,
  faDigitalOcean,
  faLinode
);
