name: Cypress tests
on:
  push:
    branches: [ main, develop ]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        machines: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npx gatsby build
          start: npx gatsby serve
          wait-on: http://localhost:9000
          record: true
          parallel: true
          group: 'Guthub Actions Run'
        env:
          # Ghost API urls
          GHOST_API_URL: ${{ secrets.GHOST_API_URL }}
          GHOST_CONTENT_API_KEY: ${{ secrets.GHOST_CONTENT_API_KEY }}
          # pass the Dashboard record key and project ID as an environment variables
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
